name: Build Splunk app

on:
  push:
    tags:
    - 'v*'
    branches:
    - main

jobs:

  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v3
      with:
        # Full clone incase we run things like 'git describe'.
        # See https://github.com/actions/checkout/issues/338
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'ksconf>=0.10,<0.11'
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Base64 Add-On for Splunk package build
      id: buildpkg
      run: |
        set -x
        echo "Build number ${{ github.run_id }}"
        ./build.py
        set +x
        echo "path=$(cat .release_path)" >> $GITHUB_OUTPUT
        echo "name=$(cat .release_name)" >> $GITHUB_OUTPUT
    - name: Create release and upload GitHub artifact
      uses: softprops/action-gh-release@v1
      if: contains(github.ref, 'tags/v')
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ${{ steps.buildpkg.outputs.path }}
